services:
  db:
    image: postgres:16-alpine
    container_name: 69-s2-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=titiwat
      - POSTGRES_PASSWORD=titiwat123
      - POSTGRES_DB=titiwat

  admin:
    image: dpage/pgadmin4
    container_name: 69-s2-admin
    ports:
      - 808080
    environment:
      - PGADMIN_DEFAULT_EMAIL=titiwat@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=titiwat123
    depends_on:
      - db
