services:
  db:
    image: postgres:16-alpine
    container_name: 69-s2-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ratchanon
      - POSTGRES_PASSWORD=pom1344968
      - POSTGRES_DB=ratchanon

  admin:
    image: dpage/pgadmin4
    container_name: 69-s2-admin
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=godsloliza007@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pom1344968
    depends_on:
      - db
